Add mark and unmark functionality.
AY2223S1-CS2103T-F12-3/tp pull request #44
Opened 2022-10-10 20:06 UTC by doimoiboi

#40

2022-10-11 03:00 UTC, yiyefyy approved these changes
Amazinggg

2022-10-13 15:58 UTC, XenonShawn requested changes
`Task` must be immutable - a new Task object should be created every time it's changed.

2022-10-13 15:58 UTC, XenonShawn commented on src/main/java/seedu/address/model/ModelManager.java
> +
Should add in the `requireNonNull` check

2022-10-13 15:58 UTC, XenonShawn commented on src/main/java/seedu/address/model/task/Task.java
> +    private boolean isDone;
`Task` is supposed to be immutable.

2022-10-13 19:05 UTC, XenonShawn approved these changes
Works, and LGTM!

2022-10-14 01:57 UTC, XenonShawn commented on src/main/java/seedu/address/model/task/Task.java
> +    public Boolean isDone() {
Should be a normal `boolean`

2022-10-14 01:57 UTC, merged